# TCL File Generated by Component Editor 21.1
# Mon Apr 15 20:58:46 EDT 2024
# DO NOT MODIFY


# 
# vga_snake "VGA_Snake" v1.0
#  2024.04.15.20:58:46
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_snake
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_snake
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME VGA_Snake
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

