	soc_system u0 (
		.clk_clk                                     (<connected-to-clk_clk>),                                     //                             clk.clk
		.hps_hps_io_emac1_inst_TX_CLK                (<connected-to-hps_hps_io_emac1_inst_TX_CLK>),                //                             hps.hps_io_emac1_inst_TX_CLK
		.hps_hps_io_emac1_inst_TXD0                  (<connected-to-hps_hps_io_emac1_inst_TXD0>),                  //                                .hps_io_emac1_inst_TXD0
		.hps_hps_io_emac1_inst_TXD1                  (<connected-to-hps_hps_io_emac1_inst_TXD1>),                  //                                .hps_io_emac1_inst_TXD1
		.hps_hps_io_emac1_inst_TXD2                  (<connected-to-hps_hps_io_emac1_inst_TXD2>),                  //                                .hps_io_emac1_inst_TXD2
		.hps_hps_io_emac1_inst_TXD3                  (<connected-to-hps_hps_io_emac1_inst_TXD3>),                  //                                .hps_io_emac1_inst_TXD3
		.hps_hps_io_emac1_inst_RXD0                  (<connected-to-hps_hps_io_emac1_inst_RXD0>),                  //                                .hps_io_emac1_inst_RXD0
		.hps_hps_io_emac1_inst_MDIO                  (<connected-to-hps_hps_io_emac1_inst_MDIO>),                  //                                .hps_io_emac1_inst_MDIO
		.hps_hps_io_emac1_inst_MDC                   (<connected-to-hps_hps_io_emac1_inst_MDC>),                   //                                .hps_io_emac1_inst_MDC
		.hps_hps_io_emac1_inst_RX_CTL                (<connected-to-hps_hps_io_emac1_inst_RX_CTL>),                //                                .hps_io_emac1_inst_RX_CTL
		.hps_hps_io_emac1_inst_TX_CTL                (<connected-to-hps_hps_io_emac1_inst_TX_CTL>),                //                                .hps_io_emac1_inst_TX_CTL
		.hps_hps_io_emac1_inst_RX_CLK                (<connected-to-hps_hps_io_emac1_inst_RX_CLK>),                //                                .hps_io_emac1_inst_RX_CLK
		.hps_hps_io_emac1_inst_RXD1                  (<connected-to-hps_hps_io_emac1_inst_RXD1>),                  //                                .hps_io_emac1_inst_RXD1
		.hps_hps_io_emac1_inst_RXD2                  (<connected-to-hps_hps_io_emac1_inst_RXD2>),                  //                                .hps_io_emac1_inst_RXD2
		.hps_hps_io_emac1_inst_RXD3                  (<connected-to-hps_hps_io_emac1_inst_RXD3>),                  //                                .hps_io_emac1_inst_RXD3
		.hps_hps_io_sdio_inst_CMD                    (<connected-to-hps_hps_io_sdio_inst_CMD>),                    //                                .hps_io_sdio_inst_CMD
		.hps_hps_io_sdio_inst_D0                     (<connected-to-hps_hps_io_sdio_inst_D0>),                     //                                .hps_io_sdio_inst_D0
		.hps_hps_io_sdio_inst_D1                     (<connected-to-hps_hps_io_sdio_inst_D1>),                     //                                .hps_io_sdio_inst_D1
		.hps_hps_io_sdio_inst_CLK                    (<connected-to-hps_hps_io_sdio_inst_CLK>),                    //                                .hps_io_sdio_inst_CLK
		.hps_hps_io_sdio_inst_D2                     (<connected-to-hps_hps_io_sdio_inst_D2>),                     //                                .hps_io_sdio_inst_D2
		.hps_hps_io_sdio_inst_D3                     (<connected-to-hps_hps_io_sdio_inst_D3>),                     //                                .hps_io_sdio_inst_D3
		.hps_hps_io_usb1_inst_D0                     (<connected-to-hps_hps_io_usb1_inst_D0>),                     //                                .hps_io_usb1_inst_D0
		.hps_hps_io_usb1_inst_D1                     (<connected-to-hps_hps_io_usb1_inst_D1>),                     //                                .hps_io_usb1_inst_D1
		.hps_hps_io_usb1_inst_D2                     (<connected-to-hps_hps_io_usb1_inst_D2>),                     //                                .hps_io_usb1_inst_D2
		.hps_hps_io_usb1_inst_D3                     (<connected-to-hps_hps_io_usb1_inst_D3>),                     //                                .hps_io_usb1_inst_D3
		.hps_hps_io_usb1_inst_D4                     (<connected-to-hps_hps_io_usb1_inst_D4>),                     //                                .hps_io_usb1_inst_D4
		.hps_hps_io_usb1_inst_D5                     (<connected-to-hps_hps_io_usb1_inst_D5>),                     //                                .hps_io_usb1_inst_D5
		.hps_hps_io_usb1_inst_D6                     (<connected-to-hps_hps_io_usb1_inst_D6>),                     //                                .hps_io_usb1_inst_D6
		.hps_hps_io_usb1_inst_D7                     (<connected-to-hps_hps_io_usb1_inst_D7>),                     //                                .hps_io_usb1_inst_D7
		.hps_hps_io_usb1_inst_CLK                    (<connected-to-hps_hps_io_usb1_inst_CLK>),                    //                                .hps_io_usb1_inst_CLK
		.hps_hps_io_usb1_inst_STP                    (<connected-to-hps_hps_io_usb1_inst_STP>),                    //                                .hps_io_usb1_inst_STP
		.hps_hps_io_usb1_inst_DIR                    (<connected-to-hps_hps_io_usb1_inst_DIR>),                    //                                .hps_io_usb1_inst_DIR
		.hps_hps_io_usb1_inst_NXT                    (<connected-to-hps_hps_io_usb1_inst_NXT>),                    //                                .hps_io_usb1_inst_NXT
		.hps_hps_io_spim1_inst_CLK                   (<connected-to-hps_hps_io_spim1_inst_CLK>),                   //                                .hps_io_spim1_inst_CLK
		.hps_hps_io_spim1_inst_MOSI                  (<connected-to-hps_hps_io_spim1_inst_MOSI>),                  //                                .hps_io_spim1_inst_MOSI
		.hps_hps_io_spim1_inst_MISO                  (<connected-to-hps_hps_io_spim1_inst_MISO>),                  //                                .hps_io_spim1_inst_MISO
		.hps_hps_io_spim1_inst_SS0                   (<connected-to-hps_hps_io_spim1_inst_SS0>),                   //                                .hps_io_spim1_inst_SS0
		.hps_hps_io_uart0_inst_RX                    (<connected-to-hps_hps_io_uart0_inst_RX>),                    //                                .hps_io_uart0_inst_RX
		.hps_hps_io_uart0_inst_TX                    (<connected-to-hps_hps_io_uart0_inst_TX>),                    //                                .hps_io_uart0_inst_TX
		.hps_hps_io_i2c0_inst_SDA                    (<connected-to-hps_hps_io_i2c0_inst_SDA>),                    //                                .hps_io_i2c0_inst_SDA
		.hps_hps_io_i2c0_inst_SCL                    (<connected-to-hps_hps_io_i2c0_inst_SCL>),                    //                                .hps_io_i2c0_inst_SCL
		.hps_hps_io_i2c1_inst_SDA                    (<connected-to-hps_hps_io_i2c1_inst_SDA>),                    //                                .hps_io_i2c1_inst_SDA
		.hps_hps_io_i2c1_inst_SCL                    (<connected-to-hps_hps_io_i2c1_inst_SCL>),                    //                                .hps_io_i2c1_inst_SCL
		.hps_hps_io_gpio_inst_GPIO09                 (<connected-to-hps_hps_io_gpio_inst_GPIO09>),                 //                                .hps_io_gpio_inst_GPIO09
		.hps_hps_io_gpio_inst_GPIO35                 (<connected-to-hps_hps_io_gpio_inst_GPIO35>),                 //                                .hps_io_gpio_inst_GPIO35
		.hps_hps_io_gpio_inst_GPIO40                 (<connected-to-hps_hps_io_gpio_inst_GPIO40>),                 //                                .hps_io_gpio_inst_GPIO40
		.hps_hps_io_gpio_inst_GPIO48                 (<connected-to-hps_hps_io_gpio_inst_GPIO48>),                 //                                .hps_io_gpio_inst_GPIO48
		.hps_hps_io_gpio_inst_GPIO53                 (<connected-to-hps_hps_io_gpio_inst_GPIO53>),                 //                                .hps_io_gpio_inst_GPIO53
		.hps_hps_io_gpio_inst_GPIO54                 (<connected-to-hps_hps_io_gpio_inst_GPIO54>),                 //                                .hps_io_gpio_inst_GPIO54
		.hps_hps_io_gpio_inst_GPIO61                 (<connected-to-hps_hps_io_gpio_inst_GPIO61>),                 //                                .hps_io_gpio_inst_GPIO61
		.hps_ddr3_mem_a                              (<connected-to-hps_ddr3_mem_a>),                              //                        hps_ddr3.mem_a
		.hps_ddr3_mem_ba                             (<connected-to-hps_ddr3_mem_ba>),                             //                                .mem_ba
		.hps_ddr3_mem_ck                             (<connected-to-hps_ddr3_mem_ck>),                             //                                .mem_ck
		.hps_ddr3_mem_ck_n                           (<connected-to-hps_ddr3_mem_ck_n>),                           //                                .mem_ck_n
		.hps_ddr3_mem_cke                            (<connected-to-hps_ddr3_mem_cke>),                            //                                .mem_cke
		.hps_ddr3_mem_cs_n                           (<connected-to-hps_ddr3_mem_cs_n>),                           //                                .mem_cs_n
		.hps_ddr3_mem_ras_n                          (<connected-to-hps_ddr3_mem_ras_n>),                          //                                .mem_ras_n
		.hps_ddr3_mem_cas_n                          (<connected-to-hps_ddr3_mem_cas_n>),                          //                                .mem_cas_n
		.hps_ddr3_mem_we_n                           (<connected-to-hps_ddr3_mem_we_n>),                           //                                .mem_we_n
		.hps_ddr3_mem_reset_n                        (<connected-to-hps_ddr3_mem_reset_n>),                        //                                .mem_reset_n
		.hps_ddr3_mem_dq                             (<connected-to-hps_ddr3_mem_dq>),                             //                                .mem_dq
		.hps_ddr3_mem_dqs                            (<connected-to-hps_ddr3_mem_dqs>),                            //                                .mem_dqs
		.hps_ddr3_mem_dqs_n                          (<connected-to-hps_ddr3_mem_dqs_n>),                          //                                .mem_dqs_n
		.hps_ddr3_mem_odt                            (<connected-to-hps_ddr3_mem_odt>),                            //                                .mem_odt
		.hps_ddr3_mem_dm                             (<connected-to-hps_ddr3_mem_dm>),                             //                                .mem_dm
		.hps_ddr3_oct_rzqin                          (<connected-to-hps_ddr3_oct_rzqin>),                          //                                .oct_rzqin
		.reset_reset_n                               (<connected-to-reset_reset_n>),                               //                           reset.reset_n
		.vga_b                                       (<connected-to-vga_b>),                                       //                             vga.b
		.vga_blank_n                                 (<connected-to-vga_blank_n>),                                 //                                .blank_n
		.vga_clk                                     (<connected-to-vga_clk>),                                     //                                .clk
		.vga_g                                       (<connected-to-vga_g>),                                       //                                .g
		.vga_hs                                      (<connected-to-vga_hs>),                                      //                                .hs
		.vga_r                                       (<connected-to-vga_r>),                                       //                                .r
		.vga_sync_n                                  (<connected-to-vga_sync_n>),                                  //                                .sync_n
		.vga_vs                                      (<connected-to-vga_vs>),                                      //                                .vs
		.snake_body_bottomleft_sprite_s1_address     (<connected-to-snake_body_bottomleft_sprite_s1_address>),     // snake_body_bottomleft_sprite_s1.address
		.snake_body_bottomleft_sprite_s1_debugaccess (<connected-to-snake_body_bottomleft_sprite_s1_debugaccess>), //                                .debugaccess
		.snake_body_bottomleft_sprite_s1_clken       (<connected-to-snake_body_bottomleft_sprite_s1_clken>),       //                                .clken
		.snake_body_bottomleft_sprite_s1_chipselect  (<connected-to-snake_body_bottomleft_sprite_s1_chipselect>),  //                                .chipselect
		.snake_body_bottomleft_sprite_s1_write       (<connected-to-snake_body_bottomleft_sprite_s1_write>),       //                                .write
		.snake_body_bottomleft_sprite_s1_readdata    (<connected-to-snake_body_bottomleft_sprite_s1_readdata>),    //                                .readdata
		.snake_body_bottomleft_sprite_s1_writedata   (<connected-to-snake_body_bottomleft_sprite_s1_writedata>),   //                                .writedata
		.snake_body_bottomleft_sprite_s1_byteenable  (<connected-to-snake_body_bottomleft_sprite_s1_byteenable>),  //                                .byteenable
		.snake_body_bottomright_snake_s1_address     (<connected-to-snake_body_bottomright_snake_s1_address>),     // snake_body_bottomright_snake_s1.address
		.snake_body_bottomright_snake_s1_debugaccess (<connected-to-snake_body_bottomright_snake_s1_debugaccess>), //                                .debugaccess
		.snake_body_bottomright_snake_s1_clken       (<connected-to-snake_body_bottomright_snake_s1_clken>),       //                                .clken
		.snake_body_bottomright_snake_s1_chipselect  (<connected-to-snake_body_bottomright_snake_s1_chipselect>),  //                                .chipselect
		.snake_body_bottomright_snake_s1_write       (<connected-to-snake_body_bottomright_snake_s1_write>),       //                                .write
		.snake_body_bottomright_snake_s1_readdata    (<connected-to-snake_body_bottomright_snake_s1_readdata>),    //                                .readdata
		.snake_body_bottomright_snake_s1_writedata   (<connected-to-snake_body_bottomright_snake_s1_writedata>),   //                                .writedata
		.snake_body_bottomright_snake_s1_byteenable  (<connected-to-snake_body_bottomright_snake_s1_byteenable>),  //                                .byteenable
		.apple_sprite_s1_address                     (<connected-to-apple_sprite_s1_address>),                     //                 apple_sprite_s1.address
		.apple_sprite_s1_debugaccess                 (<connected-to-apple_sprite_s1_debugaccess>),                 //                                .debugaccess
		.apple_sprite_s1_clken                       (<connected-to-apple_sprite_s1_clken>),                       //                                .clken
		.apple_sprite_s1_chipselect                  (<connected-to-apple_sprite_s1_chipselect>),                  //                                .chipselect
		.apple_sprite_s1_write                       (<connected-to-apple_sprite_s1_write>),                       //                                .write
		.apple_sprite_s1_readdata                    (<connected-to-apple_sprite_s1_readdata>),                    //                                .readdata
		.apple_sprite_s1_writedata                   (<connected-to-apple_sprite_s1_writedata>),                   //                                .writedata
		.apple_sprite_s1_byteenable                  (<connected-to-apple_sprite_s1_byteenable>),                  //                                .byteenable
		.snake_body_horizontal_sprite_s1_address     (<connected-to-snake_body_horizontal_sprite_s1_address>),     // snake_body_horizontal_sprite_s1.address
		.snake_body_horizontal_sprite_s1_debugaccess (<connected-to-snake_body_horizontal_sprite_s1_debugaccess>), //                                .debugaccess
		.snake_body_horizontal_sprite_s1_clken       (<connected-to-snake_body_horizontal_sprite_s1_clken>),       //                                .clken
		.snake_body_horizontal_sprite_s1_chipselect  (<connected-to-snake_body_horizontal_sprite_s1_chipselect>),  //                                .chipselect
		.snake_body_horizontal_sprite_s1_write       (<connected-to-snake_body_horizontal_sprite_s1_write>),       //                                .write
		.snake_body_horizontal_sprite_s1_readdata    (<connected-to-snake_body_horizontal_sprite_s1_readdata>),    //                                .readdata
		.snake_body_horizontal_sprite_s1_writedata   (<connected-to-snake_body_horizontal_sprite_s1_writedata>),   //                                .writedata
		.snake_body_horizontal_sprite_s1_byteenable  (<connected-to-snake_body_horizontal_sprite_s1_byteenable>),  //                                .byteenable
		.snake_body_topleft_sprite_s1_address        (<connected-to-snake_body_topleft_sprite_s1_address>),        //    snake_body_topleft_sprite_s1.address
		.snake_body_topleft_sprite_s1_debugaccess    (<connected-to-snake_body_topleft_sprite_s1_debugaccess>),    //                                .debugaccess
		.snake_body_topleft_sprite_s1_clken          (<connected-to-snake_body_topleft_sprite_s1_clken>),          //                                .clken
		.snake_body_topleft_sprite_s1_chipselect     (<connected-to-snake_body_topleft_sprite_s1_chipselect>),     //                                .chipselect
		.snake_body_topleft_sprite_s1_write          (<connected-to-snake_body_topleft_sprite_s1_write>),          //                                .write
		.snake_body_topleft_sprite_s1_readdata       (<connected-to-snake_body_topleft_sprite_s1_readdata>),       //                                .readdata
		.snake_body_topleft_sprite_s1_writedata      (<connected-to-snake_body_topleft_sprite_s1_writedata>),      //                                .writedata
		.snake_body_topleft_sprite_s1_byteenable     (<connected-to-snake_body_topleft_sprite_s1_byteenable>),     //                                .byteenable
		.snake_body_topright_sprite_s1_address       (<connected-to-snake_body_topright_sprite_s1_address>),       //   snake_body_topright_sprite_s1.address
		.snake_body_topright_sprite_s1_debugaccess   (<connected-to-snake_body_topright_sprite_s1_debugaccess>),   //                                .debugaccess
		.snake_body_topright_sprite_s1_clken         (<connected-to-snake_body_topright_sprite_s1_clken>),         //                                .clken
		.snake_body_topright_sprite_s1_chipselect    (<connected-to-snake_body_topright_sprite_s1_chipselect>),    //                                .chipselect
		.snake_body_topright_sprite_s1_write         (<connected-to-snake_body_topright_sprite_s1_write>),         //                                .write
		.snake_body_topright_sprite_s1_readdata      (<connected-to-snake_body_topright_sprite_s1_readdata>),      //                                .readdata
		.snake_body_topright_sprite_s1_writedata     (<connected-to-snake_body_topright_sprite_s1_writedata>),     //                                .writedata
		.snake_body_topright_sprite_s1_byteenable    (<connected-to-snake_body_topright_sprite_s1_byteenable>),    //                                .byteenable
		.snake_body_vertical_sprite_s1_address       (<connected-to-snake_body_vertical_sprite_s1_address>),       //   snake_body_vertical_sprite_s1.address
		.snake_body_vertical_sprite_s1_debugaccess   (<connected-to-snake_body_vertical_sprite_s1_debugaccess>),   //                                .debugaccess
		.snake_body_vertical_sprite_s1_clken         (<connected-to-snake_body_vertical_sprite_s1_clken>),         //                                .clken
		.snake_body_vertical_sprite_s1_chipselect    (<connected-to-snake_body_vertical_sprite_s1_chipselect>),    //                                .chipselect
		.snake_body_vertical_sprite_s1_write         (<connected-to-snake_body_vertical_sprite_s1_write>),         //                                .write
		.snake_body_vertical_sprite_s1_readdata      (<connected-to-snake_body_vertical_sprite_s1_readdata>),      //                                .readdata
		.snake_body_vertical_sprite_s1_writedata     (<connected-to-snake_body_vertical_sprite_s1_writedata>),     //                                .writedata
		.snake_body_vertical_sprite_s1_byteenable    (<connected-to-snake_body_vertical_sprite_s1_byteenable>),    //                                .byteenable
		.wall_sprite_s1_address                      (<connected-to-wall_sprite_s1_address>),                      //                  wall_sprite_s1.address
		.wall_sprite_s1_debugaccess                  (<connected-to-wall_sprite_s1_debugaccess>),                  //                                .debugaccess
		.wall_sprite_s1_clken                        (<connected-to-wall_sprite_s1_clken>),                        //                                .clken
		.wall_sprite_s1_chipselect                   (<connected-to-wall_sprite_s1_chipselect>),                   //                                .chipselect
		.wall_sprite_s1_write                        (<connected-to-wall_sprite_s1_write>),                        //                                .write
		.wall_sprite_s1_readdata                     (<connected-to-wall_sprite_s1_readdata>),                     //                                .readdata
		.wall_sprite_s1_writedata                    (<connected-to-wall_sprite_s1_writedata>),                    //                                .writedata
		.wall_sprite_s1_byteenable                   (<connected-to-wall_sprite_s1_byteenable>),                   //                                .byteenable
		.snake_head_down_sprite_s1_address           (<connected-to-snake_head_down_sprite_s1_address>),           //       snake_head_down_sprite_s1.address
		.snake_head_down_sprite_s1_debugaccess       (<connected-to-snake_head_down_sprite_s1_debugaccess>),       //                                .debugaccess
		.snake_head_down_sprite_s1_clken             (<connected-to-snake_head_down_sprite_s1_clken>),             //                                .clken
		.snake_head_down_sprite_s1_chipselect        (<connected-to-snake_head_down_sprite_s1_chipselect>),        //                                .chipselect
		.snake_head_down_sprite_s1_write             (<connected-to-snake_head_down_sprite_s1_write>),             //                                .write
		.snake_head_down_sprite_s1_readdata          (<connected-to-snake_head_down_sprite_s1_readdata>),          //                                .readdata
		.snake_head_down_sprite_s1_writedata         (<connected-to-snake_head_down_sprite_s1_writedata>),         //                                .writedata
		.snake_head_down_sprite_s1_byteenable        (<connected-to-snake_head_down_sprite_s1_byteenable>),        //                                .byteenable
		.snake_head_left_sprite_s1_address           (<connected-to-snake_head_left_sprite_s1_address>),           //       snake_head_left_sprite_s1.address
		.snake_head_left_sprite_s1_debugaccess       (<connected-to-snake_head_left_sprite_s1_debugaccess>),       //                                .debugaccess
		.snake_head_left_sprite_s1_clken             (<connected-to-snake_head_left_sprite_s1_clken>),             //                                .clken
		.snake_head_left_sprite_s1_chipselect        (<connected-to-snake_head_left_sprite_s1_chipselect>),        //                                .chipselect
		.snake_head_left_sprite_s1_write             (<connected-to-snake_head_left_sprite_s1_write>),             //                                .write
		.snake_head_left_sprite_s1_readdata          (<connected-to-snake_head_left_sprite_s1_readdata>),          //                                .readdata
		.snake_head_left_sprite_s1_writedata         (<connected-to-snake_head_left_sprite_s1_writedata>),         //                                .writedata
		.snake_head_left_sprite_s1_byteenable        (<connected-to-snake_head_left_sprite_s1_byteenable>),        //                                .byteenable
		.snake_head_right_sprite_s1_address          (<connected-to-snake_head_right_sprite_s1_address>),          //      snake_head_right_sprite_s1.address
		.snake_head_right_sprite_s1_debugaccess      (<connected-to-snake_head_right_sprite_s1_debugaccess>),      //                                .debugaccess
		.snake_head_right_sprite_s1_clken            (<connected-to-snake_head_right_sprite_s1_clken>),            //                                .clken
		.snake_head_right_sprite_s1_chipselect       (<connected-to-snake_head_right_sprite_s1_chipselect>),       //                                .chipselect
		.snake_head_right_sprite_s1_write            (<connected-to-snake_head_right_sprite_s1_write>),            //                                .write
		.snake_head_right_sprite_s1_readdata         (<connected-to-snake_head_right_sprite_s1_readdata>),         //                                .readdata
		.snake_head_right_sprite_s1_writedata        (<connected-to-snake_head_right_sprite_s1_writedata>),        //                                .writedata
		.snake_head_right_sprite_s1_byteenable       (<connected-to-snake_head_right_sprite_s1_byteenable>),       //                                .byteenable
		.snake_head_up_sprite_s1_address             (<connected-to-snake_head_up_sprite_s1_address>),             //         snake_head_up_sprite_s1.address
		.snake_head_up_sprite_s1_debugaccess         (<connected-to-snake_head_up_sprite_s1_debugaccess>),         //                                .debugaccess
		.snake_head_up_sprite_s1_clken               (<connected-to-snake_head_up_sprite_s1_clken>),               //                                .clken
		.snake_head_up_sprite_s1_chipselect          (<connected-to-snake_head_up_sprite_s1_chipselect>),          //                                .chipselect
		.snake_head_up_sprite_s1_write               (<connected-to-snake_head_up_sprite_s1_write>),               //                                .write
		.snake_head_up_sprite_s1_readdata            (<connected-to-snake_head_up_sprite_s1_readdata>),            //                                .readdata
		.snake_head_up_sprite_s1_writedata           (<connected-to-snake_head_up_sprite_s1_writedata>),           //                                .writedata
		.snake_head_up_sprite_s1_byteenable          (<connected-to-snake_head_up_sprite_s1_byteenable>),          //                                .byteenable
		.snake_tail_down_sprite_s1_address           (<connected-to-snake_tail_down_sprite_s1_address>),           //       snake_tail_down_sprite_s1.address
		.snake_tail_down_sprite_s1_debugaccess       (<connected-to-snake_tail_down_sprite_s1_debugaccess>),       //                                .debugaccess
		.snake_tail_down_sprite_s1_clken             (<connected-to-snake_tail_down_sprite_s1_clken>),             //                                .clken
		.snake_tail_down_sprite_s1_chipselect        (<connected-to-snake_tail_down_sprite_s1_chipselect>),        //                                .chipselect
		.snake_tail_down_sprite_s1_write             (<connected-to-snake_tail_down_sprite_s1_write>),             //                                .write
		.snake_tail_down_sprite_s1_readdata          (<connected-to-snake_tail_down_sprite_s1_readdata>),          //                                .readdata
		.snake_tail_down_sprite_s1_writedata         (<connected-to-snake_tail_down_sprite_s1_writedata>),         //                                .writedata
		.snake_tail_down_sprite_s1_byteenable        (<connected-to-snake_tail_down_sprite_s1_byteenable>),        //                                .byteenable
		.snake_tail_left_sprite_s1_address           (<connected-to-snake_tail_left_sprite_s1_address>),           //       snake_tail_left_sprite_s1.address
		.snake_tail_left_sprite_s1_debugaccess       (<connected-to-snake_tail_left_sprite_s1_debugaccess>),       //                                .debugaccess
		.snake_tail_left_sprite_s1_clken             (<connected-to-snake_tail_left_sprite_s1_clken>),             //                                .clken
		.snake_tail_left_sprite_s1_chipselect        (<connected-to-snake_tail_left_sprite_s1_chipselect>),        //                                .chipselect
		.snake_tail_left_sprite_s1_write             (<connected-to-snake_tail_left_sprite_s1_write>),             //                                .write
		.snake_tail_left_sprite_s1_readdata          (<connected-to-snake_tail_left_sprite_s1_readdata>),          //                                .readdata
		.snake_tail_left_sprite_s1_writedata         (<connected-to-snake_tail_left_sprite_s1_writedata>),         //                                .writedata
		.snake_tail_left_sprite_s1_byteenable        (<connected-to-snake_tail_left_sprite_s1_byteenable>),        //                                .byteenable
		.snake_tail_right_sprite_s1_address          (<connected-to-snake_tail_right_sprite_s1_address>),          //      snake_tail_right_sprite_s1.address
		.snake_tail_right_sprite_s1_debugaccess      (<connected-to-snake_tail_right_sprite_s1_debugaccess>),      //                                .debugaccess
		.snake_tail_right_sprite_s1_clken            (<connected-to-snake_tail_right_sprite_s1_clken>),            //                                .clken
		.snake_tail_right_sprite_s1_chipselect       (<connected-to-snake_tail_right_sprite_s1_chipselect>),       //                                .chipselect
		.snake_tail_right_sprite_s1_write            (<connected-to-snake_tail_right_sprite_s1_write>),            //                                .write
		.snake_tail_right_sprite_s1_readdata         (<connected-to-snake_tail_right_sprite_s1_readdata>),         //                                .readdata
		.snake_tail_right_sprite_s1_writedata        (<connected-to-snake_tail_right_sprite_s1_writedata>),        //                                .writedata
		.snake_tail_right_sprite_s1_byteenable       (<connected-to-snake_tail_right_sprite_s1_byteenable>)        //                                .byteenable
	);

